--Crear una función para calcular la edad del ganador de un premio nobel
CREATE OR REPLACE FUNCTION KATIA.CALCULAREDADAHORA (NACIMIENTO DATE) 
	RETURN INTEGER
	IS FECHA DATE;	
	BEGIN 
	FECHA := NOW();
	CASE
	WHEN ((MONTH(NACIMIENTO) < MONTH (FECHA))AND(DAY(NACIMIENTO)<DAY(FECHA)) THEN RETURN (YEAR(FECHA)-YEAR(NACIMIENTO))
	ELSE RETURN (YEAR(FECHA)-YEAR(NACIMIENTO)-1);
	END KATIA.CALCULAREDADAHORA;

--Crear función para calcular la edad del ganador de un premio nobel al momento de ganarlo

CREATE OR REPLACE FUNCTION KATIA.CALCULAREDAD (NACIMIENTO DATE, PREMIO DATE) RETURN EDAD 
	AS
	BEGIN 
	CASE
	WHEN ((MONTH(NACIMIENTO) < MONTH (PREMIO))AND(DAY(NACIMIENTO)<DAY(PREMIO)) THEN RETURN (YEAR(PREMIO)-YEAR(NACIMIENTO))
	ELSE RETURN (YEAR(PREMIO)-YEAR(NACIMIENTO)-1);
	END KATIA.CALCULAREDAD;


--Crear un procedimiento almacenado para insertar a un ganador de algún premio nobel

CREATE OR REPLACE PROCEDURE KATIA.INSERTAR_WINNER (ID_WIN_P NUMBER, ID_W NUMBER, ID_P NUMBER)
	
	BEGIN
	INSERT INTO KATIA.PRIZE_WINNER_TABLE (PRIZE_WINNER_ID, WINNER_ID,PRIZE_ID)
	VALUES (ID_WIN_P, ID_W, ID_P);
	END INSERTAR_WINNER;

