CREATE TABLE KATIA.WINNER_TABLE
(
    WINNER_ID         NUMBER,
    NOMBRE          NVARCHAR2 (250),
    BIRTHDAY        DATE,
    BIRTHPLACE_ID   NUMBER,
    ROLES_ID          NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;

CREATE TABLE KATIA.BIRTHPLACE_TABLE
(
    BIRTHPLACE_ID   NUMBER,
    BIRTHPLACE_DIR  NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE KATIA.PRIZE_WIN_TABLE
(
    PRIZE_ID      NUMBER,
    YEAR_D          DATE,
    MOTIVACION    NVARCHAR2 (250),
    CATEGORY_ID   NUMBER,
    COUNTRY_ID    NUMBER,
    DESCRIPTION   NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE KATIA.COUNTRY_TABLE
(
    COUNTRY_ID   NUMBER,
    COUNTRY_NAME NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE KATIA.FIELD_TABLE
(
    FIELD_ID   NUMBER,
    FIELD_DES  NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE KATIA.CATEGORY_TABLE
(
    CATEGORY_ID   NUMBER,
    CATEGORY_DES      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;



CREATE TABLE KATIA.PRIZE_TABLE
(
    PRIZE_ID   NUMBER,
    FIELD_ID    NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE KATIA.PRIZE_WINNER_TABLE
(
    PRIZE_WINNER_ID   NUMBER,
    WINNER_ID           NUMBER,
    PRIZE_ID         NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE KATIA.RESIDENCE_TABLE
(
    RESIDENCE_ID   NUMBER,
    RESIDENCE_DES  NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE KATIA.RESIDENCE_PRIZE_TABLE
(
    PRIZE_ID       NUMBER,
    RESIDENCE_ID   NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE KATIA.ROLES_TABLE
(
    ROLES_ID   NUMBER,
    ROLES      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;



CREATE UNIQUE INDEX KATIA.BIRTHPLACE_PK
    ON KATIA.BIRTHPLACE_TABLE (BIRTHPLACE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX KATIA.FIELD_PK
    ON KATIA.FIELD_TABLE (FIELD_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX KATIA.CATEGORY_PK
    ON KATIA.CATEGORY_TABLE (CATEGORY_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX KATIA.COUNTRY_PK
    ON KATIA.COUNTRY_TABLE (COUNTRY_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX KATIA.PRIZE_WINNER_PK
    ON KATIA.PRIZE_WINNER_TABLE (PRIZE_WINNER_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX KATIA.PRIZE_PK
    ON KATIA.PRIZE_TABLE (PRIZE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX KATIA.RESIDENCE_PK
    ON KATIA.RESIDENCE_TABLE (RESIDENCE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX KATIA.ROLES_PK
    ON KATIA.ROLES_TABLE (ROLES_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX KATIA.WINNER_PK
    ON KATIA.WINNER_TABLE (WINNER_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);


—-Llaves Primarias

ALTER TABLE KATIA.BIRTHPLACE_TABLE ADD (
  CONSTRAINT BIRTHPLACE_PK
  PRIMARY KEY
  (BIRTHPLACE_ID)
  USING INDEX KATIA.BIRTHPLACE_PK
  ENABLE VALIDATE);

ALTER TABLE KATIA.FIELD_TABLE ADD (
  CONSTRAINT FIELD_PK
  PRIMARY KEY
  (FIELD_ID)
  USING INDEX KATIA.FIELD_PK
  ENABLE VALIDATE);

ALTER TABLE KATIA.CATEGORY_TABLE ADD (
  CONSTRAINT CATEGORY_PK
  PRIMARY KEY
  (CATEGORY_ID)
  USING INDEX KATIA.CATEGORY_PK
  ENABLE VALIDATE);

ALTER TABLE KATIA.COUNTRY_TABLE ADD (
  CONSTRAINT COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_ID)
  USING INDEX KATIA.COUNTRY_PK
  ENABLE VALIDATE);

ALTER TABLE KATIA.PRIZE_WINNER_TABLE ADD (
  CONSTRAINT PRIZE_WINNER_PK
  PRIMARY KEY
  (PRIZE_WINNER_ID)
  USING INDEX KATIA.PRIZE_WINNER_PK
  ENABLE VALIDATE);

ALTER TABLE KATIA.PRIZE_TABLE ADD (
  CONSTRAINT PRIZE_PK
  PRIMARY KEY
  (PRIZE_ID)
  USING INDEX KATIA.PRIZE_PK
  ENABLE VALIDATE);

ALTER TABLE KATIA.RESIDENCE_TABLE ADD (
  CONSTRAINT RESIDENCE_PK
  PRIMARY KEY
  (RESIDENCE_ID)
  USING INDEX KATIA.RESIDENCE_PK
  ENABLE VALIDATE);

ALTER TABLE KATIA.ROLES_TABLE ADD (
  CONSTRAINT ROLES_PK
  PRIMARY KEY
  (ROLES_ID)
  USING INDEX KATIA.ROLES_PK
  ENABLE VALIDATE);

ALTER TABLE KATIA.WINNER_TABLE ADD (
  CONSTRAINT WINNER_PK
  PRIMARY KEY
  (WINNER_ID)
  USING INDEX KATIA.WINNER_PK
  ENABLE VALIDATE);

—-Constraints

ALTER TABLE KATIA.PRIZE_WIN_TABLE
    ADD CONSTRAINT FK_PRIZE_WIN FOREIGN KEY (CATEGORY_ID)
        REFERENCES KATIA.CATEGORY_TABLE (CATEGORY_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.PRIZE_WINNER_TABLE
    ADD CONSTRAINT FK_PRIZE_WINNER FOREIGN KEY (PRIZE_ID)
        REFERENCES KATIA.PRIZE_TABLE (PRIZE_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.RESIDENCE_PRIZE_TABLE
    ADD CONSTRAINT FK_RESIDENCE_PRIZE FOREIGN KEY (PRIZE_ID)
        REFERENCES KATIA.PRIZE_WIN_TABLE (PRIZE_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.PRIZE_FIELD_TABLE
    ADD CONSTRAINT FK_PRIZE_FIELD FOREIGN KEY (PRIZE_ID)
        REFERENCES KATIA.PRIZE_TABLE (PRIZE_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.FIELD_PRIZE_TABLE
    ADD CONSTRAINT FK_FIELD_PRIZE FOREIGN KEY (FIELD_ID)
        REFERENCES KATIA.FIELD_TABLE (FIELD_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.PRIZE_WINNER_TABLE
    ADD CONSTRAINT FK_PRIZE_WINNER FOREIGN KEY (WINNER_ID)
        REFERENCES KATIA.WINNER_TABLE (WINNER_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.WINNER_TABLE
    ADD CONSTRAINT FK_BIRTHPACE_WINNER FOREIGN KEY (BIRTHPLACE_ID)
        REFERENCES KATIA.BIRTHPLACE_TABLE (BIRTHPLACE_ID)
        ENABLE VALIDATE;


ALTER TABLE KATIA.RESIDENCE_PRIZE_TABLE
    ADD CONSTRAINT FK_RESIDENCE_PRIZE FOREIGN KEY (RESIDENCE_ID)
        REFERENCES KATIA.RESIDENCE_TABLE (RESIDENCE_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.ROLES_TABLE
    ADD CONSTRAINT FK_ROLES_WINNER FOREIGN KEY (ROLES_ID)
        REFERENCES KATIA.WINNER_TABLE (ROLES_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.PRIZE_WIN_TABLE
    ADD CONSTRAINT FK_PRIZE_COUNTRY FOREIGN KEY (COUNTRY_ID)
        REFERENCES KATIA.COUNTRY_TABLE (COUNTRY_ID)
        ENABLE VALIDATE;

ALTER TABLE KATIA.WINNER_TABLE
    ADD CONSTRAINT FK_WINNER_ROLES FOREIGN KEY (ROLES_ID)
        REFERENCES KATIA.ROLES_TABLE (ROLES_ID)
        ENABLE VALIDATE;